const getData = () => {
  return ([
    {
      header: 'We Are Food Masters',
      headerInfo: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a typespecimen book.',
      orderOnline: 'Order Online',
      locate: 'Locate our Resaturant',
      hyigeneHeader: '100 % Hygiene',
      hyigeneText: 'Cleanliness is No. 1 prioritisdj for us.',
      hyigeneImage: 'hygiene.svg',
      FineDineHeader: 'Fine Dine',
      FineDineText: 'State of the art dining experience',
      FineDineImage: 'dine.svg',
      takeAwayHeader: 'Take Away',
      takeAwayText: 'Fresh & convinient packing',
      takeAwayImage: 'takeAway.svg',
      secImage: require('../Images/fine-dine-image-1.png'),
    },
    {
      header: 'Delicious Menu',
      headerInfo: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a typespecimen book.',
      orderOnline: 'Learn More',
      locate: '',
      hyigeneHeader: '100 % Hygiene',
      hyigeneText: 'Cleanliness is No. 1 prioritisdj for us.',
      hyigeneImage: 'hygiene.svg',
      FineDineHeader: 'Fine Dine',
      FineDineText: 'State of the art dining experience',
      FineDineImage: 'dine.svg',
      takeAwayHeader: 'Take Away',
      takeAwayText: 'Fresh & convinient packing',
      takeAwayImage: 'takeAway.svg',
      secImage: require('../Images/fine-dine-image-5.png'),
    },
    {
      header: 'Our Story',
      headerInfo: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a typespecimen book.',
      orderOnline: 'Learn More',
      locate: '',
      hyigeneHeader: '100 % Hygiene',
      hyigeneText: 'Cleanliness is No. 1 prioritisdj for us.',
      hyigeneImage: 'hygiene.svg',
      FineDineHeader: 'Fine Dine',
      FineDineText: 'State of the art dining experience',
      FineDineImage: 'dine.svg',
      takeAwayHeader: 'Take Away',
      takeAwayText: 'Fresh & convinient packing',
      takeAwayImage: 'takeAway.svg',
      secImage: require('../Images/fine-dine-image-6.png'),
    },
    {
      header: 'Get in touch',
      headerInfo: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a typespecimen book.',
      orderOnline: 'Learn More',
      locate: '',
      hyigeneHeader: '100 % Hygiene',
      hyigeneText: 'Cleanliness is No. 1 prioritisdj for us.',
      hyigeneImage: 'hygiene.svg',
      FineDineHeader: 'Fine Dine',
      FineDineText: 'State of the art dining experience',
      FineDineImage: 'dine.svg',
      takeAwayHeader: 'Take Away',
      takeAwayText: 'Fresh & convinient packing',
      takeAwayImage: 'takeAway.svg',
      secImage: require('../Images/fine-dine-image-7.png'),
    }
  ]);
}

export default getData;